name: Back-end Test

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  pull_request:

jobs:
  check_flag:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Choose the Python version you want to use

    - name: Install Dependencies
      run: pip install -r back_end/saolei/requirements.txt
    
    - name: Flags
      run: python -m unittest back_end/saolei/tests.py -v

    - name: Account Link
      run: python back_end/saolei/manage.py accountlink
